# Generated by Django 3.0.6 on 2020-05-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authmanage', '0003_auto_20200516_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='detectedobj',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='owner',
            new_name='user',
        ),
    ]
