# Generated by Django 3.0.6 on 2020-05-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanage', '0004_auto_20200516_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='url_background',
        ),
        migrations.AddField(
            model_name='camera',
            name='background',
            field=models.TextField(default='background', verbose_name='фон'),
        ),
    ]
