# Generated by Django 3.0.6 on 2020-05-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanage', '0006_auto_20200518_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='local_connect',
            field=models.BooleanField(default=True, verbose_name='Локальное соединение'),
        ),
        migrations.AddField(
            model_name='camera',
            name='local_device',
            field=models.CharField(default='null local', max_length=400, verbose_name='Локальное устройство'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='url_camera',
            field=models.CharField(default='null URL', max_length=400, verbose_name='url камеры'),
        ),
    ]
