# Generated by Django 3.0.6 on 2020-05-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanage', '0008_remove_camera_local_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='url_camera',
            field=models.CharField(blank=True, default='null URL', max_length=400, verbose_name='url камеры'),
        ),
    ]
