# Generated by Django 3.0.6 on 2020-05-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanage', '0009_auto_20200519_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='url_camera',
            field=models.CharField(max_length=400, verbose_name='url камеры'),
        ),
    ]
