# Generated by Django 3.0.6 on 2020-05-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanage', '0010_auto_20200519_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='biggest_size',
            field=models.IntegerField(default=0.0, verbose_name='Минимальный размер человека'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='distance_to_undetect',
            field=models.DecimalField(decimal_places=3, default=200.0, max_digits=11, verbose_name='Максимальное расстояние от не брошенной сумки'),
        ),
    ]
