# Generated by Django 3.0.6 on 2020-05-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanage', '0012_auto_20200522_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedobj',
            name='link_to_image',
            field=models.ImageField(upload_to='', verbose_name='изображение'),
        ),
    ]
