# Generated by Django 3.0.6 on 2020-05-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanage', '0013_auto_20200524_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedobj',
            name='link_to_image',
        ),
        migrations.AddField(
            model_name='detectedobj',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_detect/%Y/%m/%D/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/%Y/%m/%D/', verbose_name='фон'),
        ),
    ]
