# Generated by Django 3.0.6 on 2020-05-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanage', '0014_auto_20200524_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='фон'),
        ),
        migrations.AlterField(
            model_name='detectedobj',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_detect/', verbose_name='изображение'),
        ),
    ]
