# Generated by Django 3.0.6 on 2020-06-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanage', '0015_auto_20200524_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='background',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='фон'),
        ),
    ]
