# Generated by Django 3.0.6 on 2020-06-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanage', '0016_auto_20200603_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedobj',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='изображение'),
        ),
    ]
